require('modules.plugins.packer')
require('modules.plugins.cmp')
require('modules.plugins.notify')
require('modules.plugins.telescope')
require('modules.plugins.treesitter')
require('modules.plugins.gitsigns')
require('modules.plugins.go')
require('modules.plugins.fm')
require('modules.plugins.illuminate')
require('modules.plugins.tmux')
require('modules.plugins.copilot')
require('modules.plugins.colorizer')
require('modules.plugins.comment')

